# Sample configuration for cli.backtester
# Adjust paths and broker settings to match your data environment.
decisions_csv: results/decisions.csv

# Optionally pad the requested history window on each side (in calendar days).
price_padding_days: 5

# Override column names returned by yfinance if needed.
price_data_columns:
  open_col: Open
  high_col: High
  low_col: Low
  close_col: Close
  volume_col: Volume
  # openinterest_col: OpenInterest

# Performance metric parameters.
risk_free_rate: 0.02            # Annual risk-free rate expressed in decimals.
trading_days_per_year: 252

cash: 100000
commission: 0.001
stake: 10
hold_value: HOLD
buy_value: BUY
sell_value: SELL

# Persist a summary CSV of per-ticker/model performance (TradingAgents + baselines)
output_csv: results/backtests.csv

# Save Backtrader charts produced during each run.
plot_output_dir: results/plots
# Optionally set a different directory for the CSV export of plot data.
# plot_data_output_dir: results/plots
# plot_style: candlestick
# plot_volume: true
# plot_dpi: 160
