# Example configuration for cli.batch_runner
# Adjust the parameters to fit your batch workload.
project: 3-AAPL Jan 25
tickers:
  - AAPL
start_date: 2025-01-02
end_date: 2025-01-03
# research_depth: 1
# analysts:
#   - market
#   - news
# llm_provider: openai
# backend_url: http://localhost:8000
shallow_thinker: gpt-4o
deep_thinker: o3
pause_seconds: 1.0
